### ISSUE TITLE
[Request] Update this code

### ISSUE THREAD

**Issue by ghost** [Sudomemo/sudomemo-utils#2]
By not updating the code, no one can benefit from your advancements or even try and make it better because there's no point in trying to fix/make better code which is outdated.

Although I also see the point that you may not want competition, I believe you'd be simply shooting yourself in the foot by doing this.

(Clarification : This was as jaames said, a misunderstanding due to the note in the readme)

**Comment by sudofox** [comment]
Er, how do you know that the code simply hasn't had any significant changes to it?

If we didn't welcome competition then it wouldn't have been released

**Comment by sudofox** [comment]
I checked, there have been some changes, but most of it is just Sudomemo-specific things that don't have any use or won't work outside of the Sudomemo environment. This has been decoupled from the main source and should work fine outside of it. Freenote uses it in their beta, I believe.

If you wish to make any contributions, feel free to follow the standard _fork-modify-PR_ procedure for Git.

Finally, I'd like to point out that much of our time has been spent working on Sudomemo and it's recent big update, and that we don't necessarily have the time to maintain this repository and create public versions whenever it's updated internally. Just like Facebook or many other companies do for their publicly-released libraries, they might not accurately reflect the ones built for and used in a production environment, and may be generalized for public use.

I'll see about translating some of our changes into this repo sometime after we release the new update and iron out any kinks it has. 

edit: details on changes from this repo to what's actually running in dev at present

For ppmParser, recent changes mostly deal with changes in how the file handles and fseek work when using streams rather than actual filesystem-based file handles.

For ugomenu, it's just debug stuff and whitespace changes

for ugoImage and ugoImageViewer -- that isn't actually used on Sudomemo itself, but we do use it during development for testing, previewing, and converting images and resources that we've designed. On Sudomemo, a lot of image and media conversion is instead designed to run as small python mini-servers to dynamically convert and serve up content to save on the overhead of loading libraries on startup. So what you see here is what we have built for general use.

We are not trying to stunt progress, as you are insinuating, by intentionally keeping things out of date on this repository.

**Comment by jaames** [comment]
I just removed that "old code" notice (I'm guessing that's what you were referring to?) in the readme since it doesn't really apply any longer, FWIW. It was left there from months (or even years) ago when these scripts were still in early development and weren't actually in use anywhere yet.

@sudofox pretty much covered the current state of things. <:
